config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root to: 'pages#index', as: :root
    end

    unauthenticated :user do
      root to: 'users/sessions#new', as: :unauthenticated_root
    end

    get '/users/sign_out' => 'users/sessions#destroy'
  end

  get 'registered_users' => 'pages#registered_users'

  post 'receive_webhooks', to: "webhooks#receive"

  get 'twitch_webhook_subscribe' => 'webhooks#twitch_subscribe'

end

app/views/pages/index.html.erb
<div class="centered white-text">
  <p>Welcome to Creative Combine's website!</p>
  <p>There is nothing here yet, but you're welcome to stay for as long as you please.<br />
  These are the details we have in your profile:</p>
  <div class="small">
    Email: <%= current_user.email %><br />
    Broadcaster Type: <%= current_user.broadcaster_type %><br />
    Description: <%= current_user.description %><br />
  </div><br />
  <%= image_tag 'CreativeCombine_Logo_WithShadow_01.png' %>
</div>

app/views/pages/registered_users.html.erb
<div class="centered white-text" style="width:70%">
  <div>
    <table class="table table-striped small">
      <thead>
        <tr>
          <td>
            Logo
          </td>
          <td>
            Name
          </td>
          <td>
            Email
          </td>
          <td>
            Type
          </td>
          <td>
            Description
          </td>
        </tr>
      </thead>
      <tbody>
        <% User.all.each do |u| %>

        <tr>
          <td>
            <%= image_tag u.image_url, class: 'logo-s' %><!---->
          </td>
          <td>
            <%= u.username %>
          </td>
          <td>
            <%= u.email %>
          </td>
          <td>
            <%= u.broadcaster_type.humanize %>
          </td>
          <td>
            <%= u.description %>
          </td>
        </tr>

        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/pages/webhook_admin.html.erb
<%= link_to twitch_webhook_subscribe_path, 'Subscribe', class: 'btn btn-sm btn-primary' %>